[package]
name = "h264-profile-level-id"
version = "0.1.0"
description = "WIP"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2018"
license = "ISC"

[dependencies]
bitpattern = "0.1.0"
log = "0.4.11"
once_cell = "1.5.2"
thiserror = "1.0.22"
